config/routes.rb
SampleApp::Application.routes.draw do

resources :users
resources :sessions, only: [:new, :create, :destroy]
resources :microposts, only: [:create, :destroy]

root to: 'static_pages#home'

match '/signup',     to: 'users#new'        
match '/signin',     to: 'sessions#new'
match '/signout',    to: 'sessions#destroy', via: :delete

match '/help',       to: 'static_pages#help'
match '/about',      to: 'static_pages#about'
match '/newsupdate', to: 'static_pages#newsupdate'

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
    @micropost = current_user.microposts.build if signed_in?
  end

  def help
  end

  def about 
  end

 def newsupdate
 end
	
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper

end

app/views/static_pages/about.html.erb
<% provide(:title, 'About us') %>
 <style>
        #main{
                background: white;
                padding: 15px;
        }
        #header{
                background: white;
                padding: 15px;
        }
     </style> 
<h1 id="header">About us</h1>
<p id="main">
	This my sample_app.<em>Please push to git</em>
</p>
<%= link_to image_tag("ownlogo.png", :alt => "Nerds") , 'http:///home/richie/Ruby/sample_app/app/assets/images' %>

app/views/static_pages/help.html.erb
<% provide(:title, 'Help') %>
<style>
        #main{
                background: white;
                padding: 15px;
        }
        #header{
                background: white;
                padding: 15px;
        }
</style> 
<h1 id="header">Help</h1>
<div id="main">
	<p>
	Get help at
		<a href ="http://railstutorial.org/help">HELP</a>.
		To ge help go to this website
		<a href ="http://google.ca">I need Help</a>
	</p>
</div>

app/views/static_pages/home.html.erb
<% provide(:title, 'Home') %> <!-- everything is referenced in application.html -->  
<!--<form class ="navbar-form navbar-left" role="search">
	<input type ="text" class="form-control" placeholder= "Search">
        <button type ="submit" class="btn btn">Submit</button> 
</form>	-->
<br/><br/><br/><br/>
<!-- if the user is signed in render this page else give him the default page -->
<style>
        #header{
                background: white;
                padding: 15px;
        }
</style> 
<% if signed_in? %>
      <div class="row" id="header">
	<aside class="span4">
	    <section>
		  <%= render 'shared/user_info' %>
	    </section>
	    <section>
		  <%= render 'shared/micropost_form' %>
	    </section>
	</aside>    
      </div>
      
 <% else %>     
<div class = "center hero-unit">
     
	<h1 class="headline_for_h1">Welcome To Forum CSHUB, Lassonde</h1>
	<h2>
		Forum page for CSHUB Members  
		<a href="#"> CSHUB</a>
	</h2>
	
	<%= link_to "Sign up now!", signup_path , :class => "btb btn-large btn-primary" %>
	
	<div class="center hero unit">
		<h3><em>Already a user? Then sign in here</em></h3>
		<%= link_to "Sign in", signin_path , :class=> "btn btn-success" %>
	</div>
	
</div>	
<%= link_to image_tag("ownlogo.png", :alt => "Nerds") , 'http:///home/richie/Ruby/sample_app/app/assets/images' %>
<% end %>

app/views/static_pages/newsupdate.html.erb
<% provide(:title, 'Current News') %>
<!DOCTYPE html>
<html>
     <style>
        #main{
                background: white;
                padding: 15px;
        }
        #header{
                background: white;
                padding: 15px;
        }
     </style>   
<h1 id="header" >Current News</h1>
<body>
        <div id="main">
                <p>
                        This is the News Page for <em>CSE 3482 .</em> Check regularly for Updates on the Course
                        <ul>
                                <li>No news as of now. Stay Safe CS bruhs</li>
                        </ul>
                </p>
        </div>        
</body>
</html>