config/routes.rb
SampleApp::Application.routes.draw do

resources :users
resources :sessions, only: [:new, :create, :destroy]
resources :microposts, only: [:create, :destroy]

root to: 'static_pages#home'

match '/signup',     to: 'users#new'        
match '/signin',     to: 'sessions#new'
match '/signout',    to: 'sessions#destroy', via: :delete

match '/help',       to: 'static_pages#help'
match '/about',      to: 'static_pages#about'
match '/newsupdate', to: 'static_pages#newsupdate'

end

app/views/layouts/_footer.html.erb
<!--<footer class ="footer">
  <nav>
    <ul>
      <li><%= link_to "About", about_path %> </li>
       <li><%= link_to "Help", help_path %> </li>
      <li> <a href= "newsupdate.html"> Current News</a></li>
    </ul>
  </nav>
  <small><p>By Richmond Frimpong</p></small>  
      
  </footer> -->
  <br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br />
  <footer>

    <ul>
        <li><a class="logo" href="https://www.linkedin.com/profile/view?id=410805035&trk=nav_responsive_tab_profile_pic">RICHMOND FRIMPONG <i>&copy; 2015</i></a></li>
        <li><%= link_to "About", about_path %> </li>
        <li><%= link_to "Help", help_path %> </li>
        <li> <a href= "newsupdate.html"> Current News</a></li>
        
        <li>
            <nav>
              <ul>
                <li><a href="richee305@yahoo.ca">Email</a></li>
                <li><a href="https://twitter.com/Richboy_Money">Twitter</a></li>
                <li><a href="https://facebook.com">Facebook</a></li>
              </ul>
            </nav>
        </li>
    </ul>

</footer>
  

app/views/layouts/_header.html.erb
  <header> <!--fixed must be changed -->
        <% link_to "sample app", root_path , :id => "logo" %>
	<div>
        <nav class="menu">
            <ul class="nav nav-pills">
              <li role="presentation" class="active"><a href="<%=root_path %>">Home</a></li>
              <li role="presentation" class="active"><a href="<%=help_path %>">Help</a></li>
             <li role="presentation" class="active"><a  href="<%=about_path %>">About</a></li> 
             <% if signed_in? %>
                <li role="presentation" class="active"><%= link_to "Users" , users_path %></li>
                <li role="presentation" class="dropdown"><a href="#" data-toggle="dropdown" class="dropdown-toggle">
                    Account  <b class="caret"></b>
                  </a>
                  <ul class="dropdown-menu">
                    <li><a href="<%= user_path(current_user) %>"><%= @current_user.name %></a></li>
                    <li><%= link_to "Settings", edit_user_path(current_user) %></li>
                    <li class="divider"></li>
                    <li><%= link_to "Sign out", signout_path, method: "delete"  %></li>
                  </ul>
                </li>
                <% else %>
                  <li><% link_to "Sign in", signin_path %></li>
		<% end %> 
            </ul>
        </nav>
	</div>
  </header>
  <!-- jquery code for nav bar problems -->
  <script>
    $(window).scroll(
    {
        previousTop: 0
    }, 
    function () {
    var currentTop = $(window).scrollTop();
    if (currentTop < this.previousTop) {
        $(".sidebar em").text("Up");
        $(".header").show();
    } else {
        $(".sidebar em").text("Down");
        $(".header").hide();
    }
    this.previousTop = currentTop;
});
  </script>
  <script>
      $('.dropdown-toggle').dropdown();
    </script>
   

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src= "http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
  <![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= full_title(yield(:title)) %></title>
  <link rel="stylesheet" type="text/css" href="http://fonts.googleapis.com/css?family=Ek+Mukta">
  <%= stylesheet_link_tag    "application", :media => "all" %> 
  <!--<link rel="stylesheet" type="text/css" href="/assets/stylesheets/custom.css.scss">-->
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  <%= render 'layouts/shim' %>
</head>
<body>
<div class ="container">
  <%= render 'layouts/header' %>
  <% flash.each do |key, value| %>
    <div class="alert alert-<%= key %>"><%= value %></div>
    <% flash.clear %>
  <% end %>
  <%= yield %>
  <%= render 'layouts/footer' %>
  <%= debug(params) if Rails.env.development? %>
</div>

</body>
</html>